### ISSUE TITLE
Error in bowtie2-build if multiple threads used

### ISSUE THREAD

**Issue by billzt** [BenLangmead/bowtie2#36] opened 2016-03-18 02:32 UTC
If I use `--threads` option in bowtie2-build, finally error occurs:
```
Settings:
  Output files: "test.*.bt2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  test.fa
Building a SMALL index
Reading reference sizes
  Time reading reference sizes: 00:00:00
Calculating joined length
Writing header
Reserving space for joined string
Joining reference sequences
  Time to join reference sequences: 00:00:00
bmax according to bmaxDivN setting: 1485
Using parameters --bmax 1114 --dcv 1024
  Doing ahead-of-time memory usage test
  Passed!  Constructing with these parameters: --bmax 1114 --dcv 1024
Constructing suffix-array element generator
Building DifferenceCoverSample
  Building sPrime
  Building sPrimeOrder
  V-Sorting samples
  V-Sorting samples time: 00:00:00
  Allocating rank array
  Ranking v-sort output
  Ranking v-sort output time: 00:00:00
  Invoking Larsson-Sadakane on ranks
  Invoking Larsson-Sadakane on ranks time: 00:00:00
  Sanity-checking and returning
Building samples
Reserving space for 12 sample suffixes
Generating random suffixes
QSorting 12 sample offsets, eliminating duplicates
QSorting sample offsets, eliminating duplicates time: 00:00:00
Multikey QSorting 12 samples
  (Using difference cover)
  Multikey QSorting samples time: 00:00:00
Calculating bucket sizes
Splitting and merging
  Splitting and merging time: 00:00:00
Split 1, merged 5; iterating...
Splitting and merging
  Splitting and merging time: 00:00:00
Avg bucket size: 741.625 (target: 1113)
Converting suffix-array elements to index image
Allocating ftab, absorbFtab
Entering Ebwt loop
Getting block 1 of 8
Getting block 2 of 8
Getting block 4 of 8
Could not open file for reading a reference graph: "test.0.saGetting block 5 of 8
"
  Reserving size (1114) for bucket 5
  Reserving size (1114) for bucket 4
  Reserving size (1114) for bucket 2
Getting block 6 of 8
Getting block 7 of 8
Getting block 3 of 8
  Calculating Z arrays for bucket 2
  Calculating Z arrays for bucket 5
  Reserving size (1114) for bucket 6
Getting block 8 of 8
  Entering block accumulator loop for bucket 5:
  Calculating Z arrays for bucket 6
  Calculating Z arrays for bucket 4
  bucket 5: 10%
  Entering block accumulator loop for bucket 2:
  Reserving size (1114) for bucket 8
  bucket 5: 20%
  Reserving size (1114) for bucket 1
  Reserving size (1114) for bucket 7
  Entering block accumulator loop for bucket 4:
  bucket 5: 30%
  Reserving size (1114) for bucket 3
  Calculating Z arrays for bucket 1
  Calculating Z arrays for bucket 7
  bucket 2: 10%
  bucket 4: 10%
  Entering block accumulator loop for bucket 1:
  bucket 2: 20%
  Entering block accumulator loop for bucket 7:
  Calculating Z arrays for bucket 3
  bucket 5: 40%
  Entering block accumulator loop for bucket 6:
  bucket 2: 30%
  Calculating Z arrays for bucket 8
  bucket 4: 20%
  bucket 5: 50%
  bucket 1: 10%
  bucket 7: 10%
  Entering block accumulator loop for bucket 8:
  bucket 1: 20%
  bucket 7: 20%
  bucket 8: 10%
  bucket 2: 40%
  bucket 4: 30%
  Entering block accumulator loop for bucket 3:
  bucket 8: 20%
  bucket 2: 50%
  bucket 6: 10%
  bucket 4: 40%
  bucket 5: 60%
  bucket 3: 10%
  bucket 2: 60%
  bucket 7: 30%
  bucket 1: 30%
  bucket 5: 70%
  bucket 3: 20%
  bucket 1: 40%
  bucket 6: 20%
  bucket 4: 50%
  bucket 8: 30%
  bucket 2: 70%
  bucket 7: 40%
  bucket 1: 50%
  bucket 6: 30%
  bucket 4: 60%
  bucket 8: 40%
  bucket 3: 30%
  bucket 1: 60%
  bucket 7: 50%
  bucket 4: 70%
  bucket 2: 80%
  bucket 3: 40%
  bucket 8: 50%
  bucket 6: 40%
  bucket 7: 60%
  bucket 3: 50%
  bucket 4: 80%
  bucket 5: 80%
  bucket 2: 90%
  bucket 3: 60%
  bucket 8: 60%
  bucket 6: 50%
  bucket 2: 100%
  bucket 8: 70%
  Sorting block of length 866 for bucket 2
  bucket 1: 70%
  bucket 5: 90%
  bucket 8: 80%
  (Using difference cover)
  bucket 3: 70%
  bucket 7: 70%
  bucket 1: 80%
  bucket 8: 90%
  bucket 6: 60%
  bucket 5: 100%
  bucket 3: 80%
  bucket 4: 90%
  bucket 6: 70%
  bucket 8: 100%
  bucket 3: 90%
  Sorting block of length 449 for bucket 8
  (Using difference cover)
  bucket 7: 80%
  bucket 1: 90%
  bucket 4: 100%
  bucket 6: 80%
  Sorting block of length 973 for bucket 4
  bucket 3: 100%
  (Using difference cover)
  bucket 6: 90%
  bucket 7: 90%
  Sorting block of length 853 for bucket 5
  (Using difference cover)
  Sorting block of length 909 for bucket 3
  (Using difference cover)
  bucket 1: 100%
  bucket 6: 100%
  bucket 7: 100%
  Sorting block of length 439 for bucket 1
  (Using difference cover)
  Sorting block of length 761 for bucket 6
  (Using difference cover)
  Sorting block of length 683 for bucket 7
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 867 for bucket 2
  Sorting block time: 00:00:00
  Sorting block time: 00:00:00
  Sorting block time: 00:00:00
  Sorting block time: 00:00:00
Returning block of 440 for bucket 1
  Sorting block time: 00:00:00
Returning block of 974 for bucket 4
Returning block of 450 for bucket 8
Returning block of 910 for bucket 3
Returning block of 854 for bucket 5
  Sorting block time: 00:00:00
  Sorting block time: 00:00:00
Returning block of 762 for bucket 6
Returning block of 684 for bucket 7
Total time for call to driver() for forward index: 00:00:00
Error: Encountered internal Bowtie 2 exception (#1)
Command: bowtie2-build --wrapper basic-0 --threads 10 test.fa test 
Deleting "test.3.bt2" file written during aborted indexing attempt.
Deleting "test.4.bt2" file written during aborted indexing attempt.
Deleting "test.1.bt2" file written during aborted indexing attempt.
Deleting "test.2.bt2" file written during aborted indexing attempt.

```

However, if I delete `--threads` option, it is OK.
```
Settings:
  Output files: "test.*.bt2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  test.fa
Building a SMALL index
Reading reference sizes
  Time reading reference sizes: 00:00:00
Calculating joined length
Writing header
Reserving space for joined string
Joining reference sequences
  Time to join reference sequences: 00:00:00
bmax according to bmaxDivN setting: 1485
Using parameters --bmax 1114 --dcv 1024
  Doing ahead-of-time memory usage test
  Passed!  Constructing with these parameters: --bmax 1114 --dcv 1024
Constructing suffix-array element generator
Building DifferenceCoverSample
  Building sPrime
  Building sPrimeOrder
  V-Sorting samples
  V-Sorting samples time: 00:00:00
  Allocating rank array
  Ranking v-sort output
  Ranking v-sort output time: 00:00:00
  Invoking Larsson-Sadakane on ranks
  Invoking Larsson-Sadakane on ranks time: 00:00:00
  Sanity-checking and returning
Building samples
Reserving space for 12 sample suffixes
Generating random suffixes
QSorting 12 sample offsets, eliminating duplicates
QSorting sample offsets, eliminating duplicates time: 00:00:00
Multikey QSorting 12 samples
  (Using difference cover)
  Multikey QSorting samples time: 00:00:00
Calculating bucket sizes
Splitting and merging
  Splitting and merging time: 00:00:00
Split 1, merged 5; iterating...
Splitting and merging
  Splitting and merging time: 00:00:00
Split 1, merged 1; iterating...
Splitting and merging
  Splitting and merging time: 00:00:00
Avg bucket size: 741.625 (target: 1113)
Converting suffix-array elements to index image
Allocating ftab, absorbFtab
Entering Ebwt loop
Getting block 1 of 8
  Reserving size (1114) for bucket 1
  Calculating Z arrays for bucket 1
  Entering block accumulator loop for bucket 1:
  bucket 1: 10%
  bucket 1: 20%
  bucket 1: 30%
  bucket 1: 40%
  bucket 1: 50%
  bucket 1: 60%
  bucket 1: 70%
  bucket 1: 80%
  bucket 1: 90%
  bucket 1: 100%
  Sorting block of length 439 for bucket 1
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 440 for bucket 1
Getting block 2 of 8
  Reserving size (1114) for bucket 2
  Calculating Z arrays for bucket 2
  Entering block accumulator loop for bucket 2:
  bucket 2: 10%
  bucket 2: 20%
  bucket 2: 30%
  bucket 2: 40%
  bucket 2: 50%
  bucket 2: 60%
  bucket 2: 70%
  bucket 2: 80%
  bucket 2: 90%
  bucket 2: 100%
  Sorting block of length 866 for bucket 2
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 867 for bucket 2
Getting block 3 of 8
  Reserving size (1114) for bucket 3
  Calculating Z arrays for bucket 3
  Entering block accumulator loop for bucket 3:
  bucket 3: 10%
  bucket 3: 20%
  bucket 3: 30%
  bucket 3: 40%
  bucket 3: 50%
  bucket 3: 60%
  bucket 3: 70%
  bucket 3: 80%
  bucket 3: 90%
  bucket 3: 100%
  Sorting block of length 1035 for bucket 3
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 1036 for bucket 3
Getting block 4 of 8
  Reserving size (1114) for bucket 4
  Calculating Z arrays for bucket 4
  Entering block accumulator loop for bucket 4:
  bucket 4: 10%
  bucket 4: 20%
  bucket 4: 30%
  bucket 4: 40%
  bucket 4: 50%
  bucket 4: 60%
  bucket 4: 70%
  bucket 4: 80%
  bucket 4: 90%
  bucket 4: 100%
  Sorting block of length 731 for bucket 4
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 732 for bucket 4
Getting block 5 of 8
  Reserving size (1114) for bucket 5
  Calculating Z arrays for bucket 5
  Entering block accumulator loop for bucket 5:
  bucket 5: 10%
  bucket 5: 20%
  bucket 5: 30%
  bucket 5: 40%
  bucket 5: 50%
  bucket 5: 60%
  bucket 5: 70%
  bucket 5: 80%
  bucket 5: 90%
  bucket 5: 100%
  Sorting block of length 969 for bucket 5
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 970 for bucket 5
Getting block 6 of 8
  Reserving size (1114) for bucket 6
  Calculating Z arrays for bucket 6
  Entering block accumulator loop for bucket 6:
  bucket 6: 10%
  bucket 6: 20%
  bucket 6: 30%
  bucket 6: 40%
  bucket 6: 50%
  bucket 6: 60%
  bucket 6: 70%
  bucket 6: 80%
  bucket 6: 90%
  bucket 6: 100%
  Sorting block of length 761 for bucket 6
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 762 for bucket 6
Getting block 7 of 8
  Reserving size (1114) for bucket 7
  Calculating Z arrays for bucket 7
  Entering block accumulator loop for bucket 7:
  bucket 7: 10%
  bucket 7: 20%
  bucket 7: 30%
  bucket 7: 40%
  bucket 7: 50%
  bucket 7: 60%
  bucket 7: 70%
  bucket 7: 80%
  bucket 7: 90%
  bucket 7: 100%
  Sorting block of length 683 for bucket 7
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 684 for bucket 7
Getting block 8 of 8
  Reserving size (1114) for bucket 8
  Calculating Z arrays for bucket 8
  Entering block accumulator loop for bucket 8:
  bucket 8: 10%
  bucket 8: 20%
  bucket 8: 30%
  bucket 8: 40%
  bucket 8: 50%
  bucket 8: 60%
  bucket 8: 70%
  bucket 8: 80%
  bucket 8: 90%
  bucket 8: 100%
  Sorting block of length 449 for bucket 8
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 450 for bucket 8
Exited Ebwt loop
fchr[A]: 0
fchr[C]: 2117
fchr[G]: 3176
fchr[T]: 4236
fchr[$]: 5940
Exiting Ebwt::buildToDisk()
Returning from initFromVector
Wrote 4196453 bytes to primary EBWT file: test.1.bt2
Wrote 1492 bytes to secondary EBWT file: test.2.bt2
Re-opening _in1 and _in2 as input streams
Returning from Ebwt constructor
Headers:
    len: 5940
    bwtLen: 5941
    sz: 1485
    bwtSz: 1486
    lineRate: 6
    offRate: 4
    offMask: 0xfffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 80
    ftabLen: 1048577
    ftabSz: 4194308
    offsLen: 372
    offsSz: 1488
    lineSz: 64
    sideSz: 64
    sideBwtSz: 48
    sideBwtLen: 192
    numSides: 31
    numLines: 31
    ebwtTotLen: 1984
    ebwtTotSz: 1984
    color: 0
    reverse: 0
Total time for call to driver() for forward index: 00:00:00
Reading reference sizes
  Time reading reference sizes: 00:00:00
Calculating joined length
Writing header
Reserving space for joined string
Joining reference sequences
  Time to join reference sequences: 00:00:00
  Time to reverse reference sequence: 00:00:00
bmax according to bmaxDivN setting: 1485
Using parameters --bmax 1114 --dcv 1024
  Doing ahead-of-time memory usage test
  Passed!  Constructing with these parameters: --bmax 1114 --dcv 1024
Constructing suffix-array element generator
Building DifferenceCoverSample
  Building sPrime
  Building sPrimeOrder
  V-Sorting samples
  V-Sorting samples time: 00:00:00
  Allocating rank array
  Ranking v-sort output
  Ranking v-sort output time: 00:00:00
  Invoking Larsson-Sadakane on ranks
  Invoking Larsson-Sadakane on ranks time: 00:00:00
  Sanity-checking and returning
Building samples
Reserving space for 12 sample suffixes
Generating random suffixes
QSorting 12 sample offsets, eliminating duplicates
QSorting sample offsets, eliminating duplicates time: 00:00:00
Multikey QSorting 12 samples
  (Using difference cover)
  Multikey QSorting samples time: 00:00:00
Calculating bucket sizes
Splitting and merging
  Splitting and merging time: 00:00:00
Avg bucket size: 741.625 (target: 1113)
Converting suffix-array elements to index image
Allocating ftab, absorbFtab
Entering Ebwt loop
Getting block 1 of 8
  Reserving size (1114) for bucket 1
  Calculating Z arrays for bucket 1
  Entering block accumulator loop for bucket 1:
  bucket 1: 10%
  bucket 1: 20%
  bucket 1: 30%
  bucket 1: 40%
  bucket 1: 50%
  bucket 1: 60%
  bucket 1: 70%
  bucket 1: 80%
  bucket 1: 90%
  bucket 1: 100%
  Sorting block of length 1020 for bucket 1
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 1021 for bucket 1
Getting block 2 of 8
  Reserving size (1114) for bucket 2
  Calculating Z arrays for bucket 2
  Entering block accumulator loop for bucket 2:
  bucket 2: 10%
  bucket 2: 20%
  bucket 2: 30%
  bucket 2: 40%
  bucket 2: 50%
  bucket 2: 60%
  bucket 2: 70%
  bucket 2: 80%
  bucket 2: 90%
  bucket 2: 100%
  Sorting block of length 469 for bucket 2
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 470 for bucket 2
Getting block 3 of 8
  Reserving size (1114) for bucket 3
  Calculating Z arrays for bucket 3
  Entering block accumulator loop for bucket 3:
  bucket 3: 10%
  bucket 3: 20%
  bucket 3: 30%
  bucket 3: 40%
  bucket 3: 50%
  bucket 3: 60%
  bucket 3: 70%
  bucket 3: 80%
  bucket 3: 90%
  bucket 3: 100%
  Sorting block of length 975 for bucket 3
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 976 for bucket 3
Getting block 4 of 8
  Reserving size (1114) for bucket 4
  Calculating Z arrays for bucket 4
  Entering block accumulator loop for bucket 4:
  bucket 4: 10%
  bucket 4: 20%
  bucket 4: 30%
  bucket 4: 40%
  bucket 4: 50%
  bucket 4: 60%
  bucket 4: 70%
  bucket 4: 80%
  bucket 4: 90%
  bucket 4: 100%
  Sorting block of length 469 for bucket 4
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 470 for bucket 4
Getting block 5 of 8
  Reserving size (1114) for bucket 5
  Calculating Z arrays for bucket 5
  Entering block accumulator loop for bucket 5:
  bucket 5: 10%
  bucket 5: 20%
  bucket 5: 30%
  bucket 5: 40%
  bucket 5: 50%
  bucket 5: 60%
  bucket 5: 70%
  bucket 5: 80%
  bucket 5: 90%
  bucket 5: 100%
  Sorting block of length 677 for bucket 5
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 678 for bucket 5
Getting block 6 of 8
  Reserving size (1114) for bucket 6
  Calculating Z arrays for bucket 6
  Entering block accumulator loop for bucket 6:
  bucket 6: 10%
  bucket 6: 20%
  bucket 6: 30%
  bucket 6: 40%
  bucket 6: 50%
  bucket 6: 60%
  bucket 6: 70%
  bucket 6: 80%
  bucket 6: 90%
  bucket 6: 100%
  Sorting block of length 964 for bucket 6
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 965 for bucket 6
Getting block 7 of 8
  Reserving size (1114) for bucket 7
  Calculating Z arrays for bucket 7
  Entering block accumulator loop for bucket 7:
  bucket 7: 10%
  bucket 7: 20%
  bucket 7: 30%
  bucket 7: 40%
  bucket 7: 50%
  bucket 7: 60%
  bucket 7: 70%
  bucket 7: 80%
  bucket 7: 90%
  bucket 7: 100%
  Sorting block of length 912 for bucket 7
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 913 for bucket 7
Getting block 8 of 8
  Reserving size (1114) for bucket 8
  Calculating Z arrays for bucket 8
  Entering block accumulator loop for bucket 8:
  bucket 8: 10%
  bucket 8: 20%
  bucket 8: 30%
  bucket 8: 40%
  bucket 8: 50%
  bucket 8: 60%
  bucket 8: 70%
  bucket 8: 80%
  bucket 8: 90%
  bucket 8: 100%
  Sorting block of length 447 for bucket 8
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 448 for bucket 8
Exited Ebwt loop
fchr[A]: 0
fchr[C]: 2117
fchr[G]: 3176
fchr[T]: 4236
fchr[$]: 5940
Exiting Ebwt::buildToDisk()
Returning from initFromVector
Wrote 4196453 bytes to primary EBWT file: test.rev.1.bt2
Wrote 1492 bytes to secondary EBWT file: test.rev.2.bt2
Re-opening _in1 and _in2 as input streams
Returning from Ebwt constructor
Headers:
    len: 5940
    bwtLen: 5941
    sz: 1485
    bwtSz: 1486
    lineRate: 6
    offRate: 4
    offMask: 0xfffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 80
    ftabLen: 1048577
    ftabSz: 4194308
    offsLen: 372
    offsSz: 1488
    lineSz: 64
    sideSz: 64
    sideBwtSz: 48
    sideBwtLen: 192
    numSides: 31
    numLines: 31
    ebwtTotLen: 1984
    ebwtTotSz: 1984
    color: 0
    reverse: 1
Total time for backward call to driver() for mirror index: 00:00:00

```

This makes me very sad...

**Comment by infphilo** [comment] 2016-03-18 11:52
Hi @billzt,

I'll look into this issue.  I haven't tested index building on such a small sequence (5940-bp long) as parallelized index building is supposed to be used for very large sequences.  I should be able to reproduce and fix this issue, but please feel free to send me your sequence file at infphilo@gmail.com.

Thanks,
Daehwan

**Comment by infphilo** [comment] 2016-03-18 14:07
Hi again @billzt, 

I tested building an index for a small sequence on my Mac and a linux system, but wasn't able to reproduce it.  Would you like to send me your file, and also let me know your bowtie2-build command and details about the system you used?

**Comment by billzt** [comment] 2016-03-19 02:13
I use the pre-compiled version in https://github.com/BenLangmead/bowtie2/releases/download/v2.2.8/bowtie2-2.2.8-linux-x86_64.zip 

My environment is CentOS 6.7

If I use `--threads 3`, it is OK. However if I use other values (2,4,5,6,7,8,...), bug all occurs. So strange.

My FASTA file:
[test.zip](https://github.com/BenLangmead/bowtie2/files/180602/test.zip)

**Comment by infphilo** [comment] 2016-03-19 14:44
Thanks, I just fixed it, with the fix available in the master branch.

@BenLangmead, the 2.2.7 release didn't have this issue, but a part of my implementation was incorrectly modified after 2.2.7 release.  This is a serious bug in the 2.2.8 release - building indexes using multithreads will very likely lead to synchronization issues.

**Comment by BenLangmead** [comment] 2016-03-19 14:46
Can you be more specific as to where the issue is, Daehwan?

**Comment by infphilo** [comment] 2016-03-19 14:55
(I just pushed my fix to the master branch)

The issue is related to an array, _done, is used to check if a ith bucket is sorted (in blockwise_sa.h).

After 2.2.7, _done array was initialized as _done = new bool[_nthreads]; 
But _done should be initialized as _done.resize(_sampleSuffs.size() + 1);

**Comment by billzt** [comment] 2016-03-22 06:45
Thank you! Do you consider to deploy a new release?

**Comment by jblachly** [comment] 2016-03-22 22:27
I also experienced this issue when building a small index (too small to need multiple cores, but I launched with 16 anyway)

Thanks for the quick fix (I haven't patched and recompiled yet)

**Comment by val-antonescu** [comment] 2016-04-22 17:38
Release 2.2.9 is fixing this issue. I will close this for now.

thanks,
Val

**Closed by val-antonescu** 2016-04-22 17:38 UTC
