### ISSUE TITLE
gzbuffer warning when using pre-compiled v2.3.2 (legacy)

### ISSUE THREAD

**Issue by ycl6** [BenLangmead/bowtie2#132] opened 2017-08-10 14:34 UTC
I downloaded "bowtie2-2.3.2-legacy-linux-x86_64.zip" and use the pre-compiled bowtie2 for alignment, but encounter the following message:
```
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
```

**Comment by coralzhang** [comment] 2017-10-24 00:46
Hi, I wonder how did you solve this problem?

**Comment by ycl6** [comment] 2017-10-24 02:11
@coralzhang I just ignore the warning, bowtie2 will continue to run despite the warning messages.

**Comment by coralzhang** [comment] 2017-10-24 02:53
Well. I ask because I wonder if changing any parameter can make it faster.

**Comment by dnbaker** [comment] 2017-10-24 03:29
You could upgrade your zlib version, allowing zlib to use a bigger buffer and therefore be faster.

**Comment by coralzhang** [comment] 2017-10-24 03:32
Then the thing is that I am not sure how to make sure that Bowtie2 is calling the new zlib.

**Comment by ch4rr0** [comment] 2017-10-24 16:36
We recently released bowtie 2 v2.3.3.1 which has both the zlib and TBB libs statically linked. You should no longer get the warnings in question when using the most recent version.

**Comment by coralzhang** [comment] 2017-10-24 16:43
OK. I guess I was using 2.3.3, rather than 2.3.3.1. I will take a look with 2.3.3.1.

**Comment by ch4rr0** [comment] 2017-10-24 16:52
if you're using 2.3.3 then it should also have the static libs.

**Comment by coralzhang** [comment] 2017-10-24 17:05
Exactly. So I wonder why I still get the warning.

**Comment by ch4rr0** [comment] 2017-10-24 17:05
can you run `ldd` on the binary and send me the output?

**Comment by coralzhang** [comment] 2017-10-24 17:16
`ldd ~/data/softwares/bowtie2-2.3.3/bowtie2`
	

> not a dynamic executable

**Comment by ch4rr0** [comment] 2017-10-24 17:17
That's the wrapper script. Try:
`ldd ~/data/softwares/bowtie2-2.3.3/bowtie2-align-s`

**Comment by coralzhang** [comment] 2017-10-24 17:18
Here it is

`$ ldd ~/data/softwares/bowtie2-2.3.3/bowtie2-align-s
	linux-vdso.so.1 =>  (0x00007fff7985b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f047e2f6000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f047dff4000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f047dddd000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f047da1c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f047e523000)`

**Comment by ch4rr0** [comment] 2017-10-24 17:36
2.3.3 does have the static libraries, but I must have linked against a slightly older version of zlib that triggers this warning. I confirmed that the issue is resolved with 2.3.3.1. Thank you pointing this out.
```
bowtie2-2.3.3.1# ./bowtie2 -x example/index/lambda_virus example/reads/longreads.fq.gz -S /dev/null
6000 reads; of these:
  6000 (100.00%) were unpaired; of these:
    287 (4.78%) aligned 0 times
    5713 (95.22%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
95.22% overall alignment rate
```

```
bowtie2-2.3.3# ./bowtie2 -x example/index/lambda_virus example/reads/longreads.fq.gz -S /dev/null
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
6000 reads; of these:
  6000 (100.00%) were unpaired; of these:
    287 (4.78%) aligned 0 times
    5713 (95.22%) aligned exactly 1 time
    0 (0.00%) aligned >1 times
95.22% overall alignment rate
```

**Comment by coralzhang** [comment] 2017-10-24 17:42
Great. I will update now. Just out of curiosity, this should not slow down the process too much or make the results any kind of wrong, right?
Thank you very much for your kindly and timely support.

**Comment by ch4rr0** [comment] 2017-10-24 17:43
It should not affect the results of the alignment, and unless you're running a massive alignment performance degradation should be negligible.

**Comment by coralzhang** [comment] 2017-10-24 17:46
I have a pairend WGBS data of size about 8GB, i.e. 4GB for each end. So this is one step fo DMR calling. It is still running and it has been running for about 15 hours. I asked because I am not sure what is making it so slow.

**Comment by ch4rr0** [comment] 2017-10-24 17:49
Are you taking advantage of multi-threading when running your alignment?

**Comment by coralzhang** [comment] 2017-10-24 18:21
Not now. I am about to test it.

**Comment by BenLangmead** [comment] 2017-12-13 20:21
Closing for now.  Let us know if there are lingering issues.

**Closed by BenLangmead** 2017-12-13 20:21 UTC
